### PR TITLE
Fix jumpy text and add smooth scroll for navigation

### PR DESCRIPTION
**Pull request by Pustur**
Hi, i'm the guy from "feedback friday".

I messed around a bit with your code and fixed the jumpy text and added the smooth scroll for the navigation.
I saw that you use the tag `center` a lot, [DON'T](http://www.w3schools.com/tags/tag_center.asp).
Keep it up and have fun!

### CODE REVIEW

**Comment by 13lank-null** [comment]
Hey awesome man thanks very much for the changes. Funny story about the center tag i just read up on it yesterday about it not being supported by HTML5 haha but ill go and change them and add centering through CSS instead. 

Also if i may ask when you commited how did you commit multiple lines for a single file commit like you did above for the jumpy text fix. As im still learning a bit more about git and github.

**Comment by Pustur** [comment]
@13lank-null Great to hear you're going to fix the `center` tags.
For a multiline commit (if you are only using the command line) you can type
```
git commit
```
and it will bring up a [vim editor](https://en.wikipedia.org/wiki/Vim_(text_editor)), the first line is the "summary" and the subsequent lines are for the "description"

If you are on a desktop client like i do, it's even easier and faster thanks to the intuitive interface: github desktop

**Comment by 13lank-null** [comment]
Yea I can assume the desktop version would be easier as it GUI based but i'm trying to work more of terminal. I don't know why but it makes me feel hackerish haha. 

As for multiline comments I kinda figured it was vim as it happened to me before in which i couldn't for the life of me get out of vim and finish committing my commits but awesome know i know how its setup. Is there a way to commit all the commits one by one and  making it autonomous and just simply have to input messages?

**Comment by Pustur** [comment]
@13lank-null I don't know about that, i usually don't make a ton of commits, i prefer to work on a feature (that might spread across multiple files) and when i'm done i commit all the files and give it (if necessary) a detailed description about what i did and where.

BTW i was in the same position as you and for the first few times i only used the terminal. But then i decided to try [Github Desktop](https://desktop.github.com/) and i find it to be way easier and faster.
I think that it's best to know the basics of git from the terminal, but after a while you should seek what you find more productive instead of what "seems more impressive and hackerish" 😛

**Pull request merged**
